name: Refresh MD img

on:
  
  schedule:
    - cron:  '* * */1 * *'  
  workflow_dispatch:

permissions:
  contents: write

concurrency: refresh-markdown  

jobs:
  update-md:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'       
        extensions: mbstring     
        tools: composer          

    - name: Run updater
      run: php scripts/update_readme.php

    - name: Commit & push if changed
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name  "github-actions[bot]"

        if [[ -n $(git status --porcelain) ]]; then
          git add README.md
          git commit -m "chore(readme): automated refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ') [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
